services:
 fastapi:
   image: virajdocker/fastapi 
   build:
    context: .
    dockerfile: Dockerfile  
   ports: 
      - 8000:8000   
 streamlit:
   image: virajdocker/streamlit 
   build:
     context: streamlit_app
     dockerfile: Dockerfile  
   ports: 
     - 8501:8501   
   environment:
     API_URL: http://fastapi:8000