name: MLops CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Data Processing
        run: |
          python src/data/run_processing.py \
            --input data/raw/housing.csv \
            --output data/processed/cleaned_house_data.csv
      
      - name: Do Feature Engineering
        run: |
          python src/features/engineer.py \
            --input data/processed/cleaned_house_data.csv \
            --output data/processed/features_house_data.csv \
            --preprocessor models/trained/preprocessor.pkl

      - name: Setup MLFlow
        run: |
          docker pull ghcr.io/mlflow/mlflow:latest
          docker run -d -p 5555:5000 --name mlflow-server ghcr.io/mlflow/mlflow:latest\
            mlflow server --host 0.0.0.0 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /tmp/mlruns

      - name: Train The Model
        run: |
          python src/models/train_model.py \
            --config configs/model_config.yaml \
            --data data/processed/features_house_data.csv \
            --models-dir models \
            --mlflow-tracking-uri http://localhost:5555 \

      - name: Cleanup MLFlow
        run: |
          docker stop mlflow-server
          docker rm mlflow-server
          docker rmi ghcr.io/mlflow/mlflow:latest

          
            